spring:
  datasource:
    driverClassName: org.h2.Driver
    password: jayesh
    url: jdbc:h2:mem:insPlanDB
    username: jayesh
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format-sql: true
    show-sql: true

server:
  port: 9090    
  
plan-api: 
 messages:
   planSaved: Plan Saved Successfully
   planNotSaved: Plan Not Saved Successfully
   planUpdated: Paln Updated
   planNotUpdated: Paln Not Updated
   planDeleted: Plan deleted
   planNotDeleted: Plan Not deleted
   planStatusChnaged: Plan Status Chnaged Successfully
   planStatusNotChnaged: Plan Status Chnaged Successfully
